---

- name: Network Getting Started First Playbook Extended
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: {{host}}
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World