---

- name: Pull image to deploy
  gather_facts: false
  hosts: "{{host}}"
  tasks:
    - name: Print message
      debug:
        msg: Hello we are inside the machine to deploy, pulling from {{docker_image}}
    - name: Stop a data container
      docker_container:
        name: "{{app_name}}"
        image: "{{docker_image}}"
        ports:
        - "{{app_port}}:{{app_port}}"
        state: stopped
    - name: Tag old image
      shell: "docker tag {{docker_image}} {{harbor_image_url}}:{{back_up_tag}}"
    - name: Backup old docker_image
      shell: "docker push {{harbor_image_url}}:{{back_up_tag}}"
    - name: Remove image
      docker_image:
        state: absent
        name: "{{harbor_image_url}}"
        tag: "{{current_running_tag}}"
    - name: pull an image
      docker_image:
        name: "{{docker_image}}"
    - name: Create a data container
      docker_container:
        name: "{{app_name}}"
        image: "{{docker_image}}"
        ports:
        - "{{app_port}}:{{app_port}}"
        state: stopped
        restart: yes
