---

- name: Pull image to deploy
  gather_facts: false
  hosts: "{{host}}"
  tasks:
    - name: Print message
      debug:
        msg: Hello we are inside the machine to deploy, pulling from {{docker_image}}
    - name: pull an image
      docker_image:
        name: "{{docker_image}}"
    - name: Stop Existing Container
      docker_container:
        name: mycontainer
        state: stopped
    - name: Create a data container
      docker_container:
        name: "{{app_name}}"
        image: "{{docker_image}}"
        ports:
        - "{{app_port}}:{{app_port}}"
