---

- name: Pull image to deploy
  gather_facts: false
  hosts: "{{host}}"
  tasks:
    - name: Print message
      debug:
        msg: Hello we are inside the machine to deploy, pulling from {{docker_image}}
